version: '3.4'

services:
  eshopdb:
    image: postgres

  seq:
    image: datalust/seq:latest

  distributedcache:
    image: redis

  messagebus:
    image: rabbitmq:management

volumes:
  postgres_eshopdb:
